<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>🎐 🕺🏽 🔷 [DotNetBook] Acara pengecualian dan cara mendapatkan StackOverflow dan ExecutionEngineException dari awal 👇🏽 👩🏿‍🌾 👩🏻‍🤝‍👨🏽</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Acara Pengecualian 


 Dalam kasus umum, kita tidak selalu tahu tentang pengecualian yang akan terjadi dalam program kita karena hampir selalu kita me...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>[DotNetBook] Acara pengecualian dan cara mendapatkan StackOverflow dan ExecutionEngineException dari awal</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/clrium/blog/419929/"><img width="350" src="https://habrastorage.org/webt/vh/7j/tq/vh7jtqhzbne4h3rjhprca2pruhu.png" align="left"><br><h2 id="sobytiya-ob-isklyuchitelnyh-situaciyah">  Acara Pengecualian </h2><br><p> Dalam kasus umum, kita tidak selalu tahu tentang pengecualian yang akan terjadi dalam program kita karena hampir selalu kita menggunakan sesuatu yang ditulis oleh orang lain dan yang ada di subsistem dan perpustakaan lain.  Tidak hanya akan ada berbagai situasi dalam kode Anda sendiri, dalam kode perpustakaan lain, ada juga banyak masalah yang terkait dengan pelaksanaan kode di domain yang terisolasi.  Dan hanya dalam kasus ini akan sangat berguna untuk dapat menerima data tentang pengoperasian kode yang terisolasi.  Bagaimanapun, situasi mungkin cukup nyata ketika kode pihak ketiga mencegat semua kesalahan tanpa kecuali, menenggelamkan <code>fault</code> mereka <code>fault</code> blok: </p><br><pre> <code class="plaintext hljs">try { // ... } catch { // do nothing, just to make code call more safe }</code> </pre> <br><p>  Dalam situasi seperti itu, eksekusi kode mungkin tidak lagi seaman kelihatannya, tetapi kami tidak memiliki pesan tentang masalah apa pun.  Opsi kedua adalah ketika aplikasi menekan beberapa pengecualian, bahkan legal.  Dan hasilnya - pengecualian berikut di tempat acak akan menyebabkan aplikasi crash di masa depan dari kesalahan yang tampaknya acak.  Di sini saya ingin tahu apa latar belakang kesalahan ini.  Apa jalannya acara menyebabkan situasi ini.  Dan salah satu cara untuk membuat ini mungkin adalah dengan menggunakan acara tambahan yang berhubungan dengan situasi luar biasa: <code>AppDomain.FirstChanceException</code> dan <code>AppDomain.UnhandledException</code> . </p><br><blockquote><h3>  Catatan </h3><br>  Bab yang diterbitkan di Habré tidak diperbarui dan, mungkin, sudah agak ketinggalan zaman.  Dan karena itu, silakan buka teks asli untuk teks yang lebih baru: <br><br><ul><li><img src="https://habrastorage.org/webt/3q/6g/qa/3q6gqaz40qx-jzscjf3jbxatxhg.png">  CLR Book: <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">GitHub, daftar isi</a> </li><li><img src="https://habrastorage.org/webt/3q/6g/qa/3q6gqaz40qx-jzscjf3jbxatxhg.png">  Buku CLR: <a href="">GitHub, bab</a> </li><li><img src="https://habrastorage.org/webt/eo/6g/eo/eo6geog0tg5ernqmv2lcmufefta.png">  Rilis 0,5.2 buku, PDF: <a href="">Rilis GitHub</a> </li></ul><br></blockquote><p> <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u="><img src="https://habrastorage.org/getpro/habr/post_images/97f/1d3/cf0/97f1d3cf0e2a6bf007066eb60a789c31.png"></a> </p><a name="habracut"></a><br><p>  Bahkan, ketika Anda "melempar pengecualian", metode biasa dari beberapa subsistem <code>Throw</code> internal disebut, yang di dalamnya sendiri melakukan operasi berikut: </p><br><ul><li>  Melemparkan <code>AppDomain.FirstChanceException</code> </li><li>  Mencari filter yang cocok dalam rantai penangan </li><li>  Menyebabkan pawang memutar gulungan ke bingkai yang diinginkan. </li><li>  Jika tidak ada penangan yang ditemukan, <code>AppDomain.UnhandledException</code> , menabrak utas di mana pengecualian terjadi. </li></ul><br><p>  Seseorang harus segera membuat reservasi ketika menjawab pertanyaan yang menyiksa banyak pikiran: apakah mungkin untuk membatalkan pengecualian yang terjadi pada kode yang tidak terkontrol yang dijalankan dalam domain terisolasi tanpa dengan demikian memutus utas di mana pengecualian ini dilemparkan?  Jawabannya singkat dan sederhana: tidak.  Jika pengecualian tidak ditangkap pada seluruh rentang metode yang disebut, itu tidak bisa ditangani secara prinsip.  Jika tidak, situasi aneh muncul: jika kita menggunakan <code>AppDomain.FirstChanceException</code> menangani (semacam <code>catch</code> sintetis) pengecualian, maka bingkai mana yang harus ditumpuk dengan tumpukan ulir?  Bagaimana cara mengatur ini sebagai bagian dari aturan .NET CLR?  Tidak mungkin.  Itu tidak mungkin.  Satu-satunya hal yang dapat kita lakukan adalah mencatat informasi yang diterima untuk penelitian selanjutnya. </p><br><p>  Hal kedua untuk berbicara tentang "darat" adalah mengapa acara ini diperkenalkan bukan di <code>Thread</code> , tetapi di <code>AppDomain</code> .  Lagi pula, jika Anda mengikuti logika, pengecualian muncul di mana?  Dalam alur eksekusi perintah.  Yaitu  sebenarnya <code>Thread</code> .  Jadi mengapa domain memiliki masalah?  Jawabannya sangat sederhana: untuk situasi apa <code>AppDomain.FirstChanceException</code> dan <code>AppDomain.UnhandledException</code> ?  Antara lain - untuk membuat kotak pasir untuk plugin.  Yaitu  untuk situasi ketika ada <code>AppDomain</code> tertentu yang dikonfigurasi untuk PartialTrust.  Apa pun bisa terjadi di dalam AppDomain ini: utas dapat dibuat di sana setiap saat, atau yang ada dari ThreadPool dapat digunakan.  Kemudian ternyata kami, berada di luar proses ini (kami tidak menulis kode itu), kami tidak dapat berlangganan ke acara arus internal.  Hanya karena kita tidak tahu aliran apa yang diciptakan di sana.  Tetapi kami dijamin memiliki <code>AppDomain</code> yang mengatur kotak pasir dan tautan yang kami miliki. </p><br><p>  Jadi, pada kenyataannya, kita diberikan dua peristiwa regional: sesuatu terjadi yang tidak seharusnya ( <code>FirstChanceExecption</code> ) dan "semuanya buruk", tidak ada yang menangani pengecualian: itu tidak disediakan.  Oleh karena itu, alur eksekusi perintah tidak masuk akal dan itu ( <code>Thread</code> ) akan dikirim. </p><br><p>  Apa yang bisa diperoleh dengan memiliki acara-acara ini dan mengapa itu buruk bahwa pengembang memotong acara ini? </p><br><h3 id="appdomainfirstchanceexception">  AppDomain.FirstChanceException </h3><br><p>  Acara ini pada dasarnya bersifat informasi dan tidak dapat "diproses".  Tugasnya adalah untuk memberi tahu Anda bahwa pengecualian telah terjadi dalam domain ini dan akan mulai diproses oleh kode aplikasi setelah memproses acara tersebut.  Eksekusinya membawa beberapa fitur yang harus diingat selama desain prosesor. </p><br><p>  Tapi mari kita lihat contoh sintetik sederhana dari pemrosesan: </p><br><pre> <code class="plaintext hljs">void Main() { var counter = 0; AppDomain.CurrentDomain.FirstChanceException += (_, args) =&gt; { Console.WriteLine(args.Exception.Message); if(++counter == 1) { throw new ArgumentOutOfRangeException(); } }; throw new Exception("Hello!"); }</code> </pre> <br><p>  Apa yang luar biasa dari kode ini?  Di mana pun beberapa kode mengeluarkan pengecualian, hal pertama yang terjadi adalah mencatatnya ke konsol.  Yaitu  bahkan jika Anda lupa atau tidak bisa membayangkan menangani beberapa jenis pengecualian, itu akan tetap muncul di log peristiwa yang Anda kelola.  Yang kedua adalah kondisi yang agak aneh untuk melempar pengecualian internal.  Masalahnya adalah bahwa di dalam penangan <code>FirstChanceException</code> Anda tidak bisa hanya melempar dan melempar satu pengecualian lagi.  Sebaliknya, bahkan ini: di dalam penangan FirstChanceException, Anda <em>tidak dapat</em> melemparkan setidaknya pengecualian apa pun.  Jika Anda melakukannya, ada dua kemungkinan acara.  Pada awalnya, jika tidak ada kondisi <code>if(++counter == 1)</code> , kita akan mendapatkan <code>FirstChanceException</code> tanpa <code>FirstChanceException</code> untuk <code>ArgumentOutOfRangeException</code> semuanya baru.  Apa artinya ini?  Ini berarti bahwa pada tahap tertentu kita akan mendapatkan <code>StackOverflowException</code> : <code>throw new Exception("Hello!")</code> <code>FirstChanceException</code> CLR Throw, yang melempar <code>FirstChanceException</code> , yang melempar <code>Throw</code> sudah untuk <code>ArgumentOutOfRangeException</code> dan kemudian berulang.  Opsi kedua - kami membela diri dengan kedalaman rekursi menggunakan kondisi <code>counter</code> .  Yaitu  dalam hal ini, kami hanya melempar pengecualian satu kali.  Hasilnya lebih dari yang tidak terduga: kami mendapatkan pengecualian yang benar-benar berfungsi di dalam instruksi <code>Throw</code> .  Dan apa yang paling cocok untuk jenis kesalahan ini?  Menurut ECMA-335, jika sebuah instruksi dilemparkan ke dalam pengecualian, sebuah <code>ExecutionEngineException</code> harus dibuang!  Tetapi kami tidak dapat menangani situasi yang luar biasa ini.  Ini menyebabkan crash lengkap dari aplikasi.  Apa saja opsi pemrosesan aman yang kami miliki? </p><br><p>  Hal pertama yang terlintas dalam pikiran adalah untuk mengatur blok <code>try-catch</code> pada seluruh kode penangan <code>FirstChanceException</code> : </p><br><pre> <code class="plaintext hljs">void Main() { var fceStarted = false; var sync = new object(); EventHandler&lt;FirstChanceExceptionEventArgs&gt; handler; handler = new EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt; { lock (sync) { if (fceStarted) { //     - ,        -      , //   try  . Console.WriteLine($"FirstChanceException inside FirstChanceException ({args.Exception.GetType().FullName})"); return; } fceStarted = true; try { //     . ,   Console.WriteLine(args.Exception.Message); throw new ArgumentOutOfRangeException(); } catch (Exception exception) { //       Console.WriteLine("Success"); } finally { fceStarted = false; } } }); AppDomain.CurrentDomain.FirstChanceException += handler; try { throw new Exception("Hello!"); } finally { AppDomain.CurrentDomain.FirstChanceException -= handler; } } OUTPUT: Hello! Specified argument was out of the range of valid values. FirstChanceException inside FirstChanceException (System.ArgumentOutOfRangeException) Success !Exception: Hello!</code> </pre> <br><p>  Yaitu  di satu sisi, kami memiliki kode untuk menangani acara <code>FirstChanceException</code> , dan di sisi lain, kami memiliki kode tambahan untuk menangani pengecualian di <code>FirstChanceException</code> itu sendiri.  Namun, teknik logging untuk kedua situasi harus berbeda.  Jika logging pemrosesan acara dapat berjalan sesuai keinginan Anda, maka pemrosesan kesalahan pemrosesan logika <code>FirstChanceException</code> harus berjalan tanpa kecuali pada prinsipnya.  Hal kedua yang mungkin Anda perhatikan adalah sinkronisasi antar utas.  Ini mungkin menimbulkan pertanyaan: mengapa ada di sini jika ada pengecualian yang dilemparkan ke utas apa pun, yang berarti bahwa <code>FirstChanceException</code> harus aman utas.  Namun, semuanya tidak begitu ceria.  <code>FirstChanceException</code> kami miliki di AppDomain.  Dan ini berarti bahwa itu terjadi untuk utas yang dimulai dalam domain tertentu.  Yaitu  jika kami memiliki domain tempat beberapa utas dimulai, maka <code>FirstChanceException</code> dapat berjalan paralel.  Dan ini berarti bahwa kita perlu melindungi diri kita dengan sinkronisasi: misalnya, menggunakan <code>lock</code> . </p><br><p>  Cara kedua adalah mencoba mengalihkan pemrosesan ke utas tetangga yang memiliki domain aplikasi berbeda.  Namun, perlu disebutkan bahwa dengan implementasi seperti itu, kita harus membangun domain khusus untuk tugas ini sehingga tidak berfungsi sehingga aliran lain yang berfungsi dapat menempatkan domain ini: </p><br><pre> <code class="plaintext hljs">static void Main() { using (ApplicationLogger.Go(AppDomain.CurrentDomain)) { throw new Exception("Hello!"); } } public class ApplicationLogger : MarshalByRefObject { ConcurrentQueue&lt;Exception&gt; queue = new ConcurrentQueue&lt;Exception&gt;(); CancellationTokenSource cancellation; ManualResetEvent @event; public void LogFCE(Exception message) { queue.Enqueue(message); } private void StartThread() { cancellation = new CancellationTokenSource(); @event = new ManualResetEvent(false); var thread = new Thread(() =&gt; { while (!cancellation.IsCancellationRequested) { if (queue.TryDequeue(out var exception)) { Console.WriteLine(exception.Message); } Thread.Yield(); } @event.Set(); }); thread.Start(); } private void StopAndWait() { cancellation.Cancel(); @event.WaitOne(); } public static IDisposable Go(AppDomain observable) { var dom = AppDomain.CreateDomain("ApplicationLogger", null, new AppDomainSetup { ApplicationBase = AppDomain.CurrentDomain.BaseDirectory, }); var proxy = (ApplicationLogger)dom.CreateInstanceAndUnwrap(typeof(ApplicationLogger).Assembly.FullName, typeof(ApplicationLogger).FullName); proxy.StartThread(); var subscription = new EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt; { proxy.LogFCE(args.Exception); }); observable.FirstChanceException += subscription; return new Subscription(() =&gt; { observable.FirstChanceException -= subscription; proxy.StopAndWait(); }); } private class Subscription : IDisposable { Action act; public Subscription (Action act) { this.act = act; } public void Dispose() { act(); } } }</code> </pre> <br><p>  Dalam hal ini, penanganan <code>FirstChanceException</code> seaman mungkin: di utas tetangga yang merupakan milik domain tetangga.  Dalam hal ini, kesalahan dalam memproses pesan tidak dapat menurunkan alur kerja aplikasi.  Plus, Anda dapat secara terpisah mendengarkan UnhandledException dari domain pencatatan pesan: kesalahan fatal selama pencatatan tidak akan menurunkan seluruh aplikasi. </p><br><h3 id="appdomainunhandledexception">  AppDomain.UnhandledException </h3><br><p>  Pesan kedua yang bisa kami tangkap dan yang berhubungan dengan penanganan pengecualian adalah <code>AppDomain.UnhandledException</code> .  Pesan ini adalah berita yang sangat buruk bagi kami karena itu berarti bahwa tidak ada orang yang bisa menemukan cara untuk menangani kesalahan di utas tertentu.  Juga, jika situasi seperti itu terjadi, yang bisa kita lakukan adalah "menghapus" konsekuensi dari kesalahan semacam itu.  Yaitu  dengan cara apa pun untuk membersihkan sumber daya yang hanya dimiliki oleh aliran ini jika ada yang dibuat.  Namun, situasi yang lebih baik adalah menangani pengecualian saat berada di akar utas tanpa memblokir utas.  Yaitu  intinya menempatkan <code>try-catch</code> .  Mari kita coba mempertimbangkan kesesuaian perilaku ini. </p><br><p>  Misalkan kita memiliki perpustakaan yang perlu membuat utas dan mengimplementasikan beberapa jenis logika dalam utas ini.  Kami, sebagai pengguna perpustakaan ini, hanya tertarik untuk menjamin panggilan API serta menerima pesan kesalahan.  Jika pustaka akan mogok aliran tanpa memberi tahu tentang hal itu, ini tidak dapat banyak membantu kami.  Selain itu, runtuhnya aliran akan mengarah ke pesan <code>AppDomain.UnhandledException</code> , di mana tidak ada informasi tentang aliran tertentu yang berada di sisinya.  Jika kita berbicara tentang kode kita, aliran yang macet juga tidak akan berguna bagi kita.  Bagaimanapun, saya tidak memenuhi kebutuhan untuk ini.  Tugas kami adalah memproses kesalahan dengan benar, mengirim informasi tentang kemunculannya ke log kesalahan dan menghentikan aliran dengan benar.  Yaitu  pada dasarnya bungkus metode dengan mana thread dimulai pada <code>try-catch</code> : </p><br><pre> <code class="plaintext hljs"> ThreadPool.QueueUserWorkitem(_ =&gt; { using(Disposables aggregator = ...){ try { // do work here, plus: aggregator.Add(subscriptions); aggregator.Add(dependantResources); } catch (Exception ex) { logger.Error(ex, "Unhandled exception"); } } });</code> </pre> <br><p>  Dalam skema seperti itu, kita mendapatkan apa yang kita butuhkan: di satu sisi, kita tidak akan merusak arus.  Di sisi lain, bersihkan sumber daya lokal dengan benar jika dibuat.  Nah, di lampiran - kami mengatur pencatatan kesalahan yang diterima.  Tapi tunggu, katamu.  Entah bagaimana Anda terkenal memunculkan masalah <code>AppDomain.UnhandledException</code> event.  Apakah ini benar-benar tidak perlu sama sekali?  Itu perlu.  Tetapi hanya untuk menginformasikan bahwa kami lupa untuk membungkus beberapa utas dalam <code>try-catch</code> dengan semua logika yang diperlukan.  Dengan segalanya: dengan penebangan dan pemurnian sumber daya.  Kalau tidak, itu akan sepenuhnya salah: untuk mengambil dan memadamkan semua pengecualian, seolah-olah mereka tidak ada sama sekali. </p><br><blockquote><h3>  Tautan ke seluruh buku </h3><br><ul><li><img src="https://habrastorage.org/webt/3q/6g/qa/3q6gqaz40qx-jzscjf3jbxatxhg.png">  Buku CLR: <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">GitHub</a> </li><li><img src="https://habrastorage.org/webt/eo/6g/eo/eo6geog0tg5ernqmv2lcmufefta.png">  Rilis 0,5.0 buku, PDF: <a href="">Rilis GitHub</a> </li></ul><br></blockquote><p> <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u="><img src="https://habrastorage.org/getpro/habr/post_images/97f/1d3/cf0/97f1d3cf0e2a6bf007066eb60a789c31.png"></a> </p></div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/id419929/">https://habr.com/ru/post/id419929/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../id419919/index.html">Kontrol versi di dalam SQL Server</a></li>
<li><a href="../id419921/index.html">Cara menjatuhkan 10 juta paket per detik</a></li>
<li><a href="../id419923/index.html">Pekerjaan sementara saya, jam tangan motherboard</a></li>
<li><a href="../id419925/index.html">Kontrol versi file individual menggunakan GitHub Gist</a></li>
<li><a href="../id419927/index.html">[DotNetBook] Pengecualian: Jenis Arsitektur Sistem</a></li>
<li><a href="../id419931/index.html">[DotNetBook] Saatnya menghibur cerita: situasi yang sangat luar biasa</a></li>
<li><a href="../id419933/index.html">Cara melakukan pencarian pengguna di Github menggunakan Angular</a></li>
<li><a href="../id419935/index.html">Tepat sekali TIDAK persis sama: analisis artikel</a></li>
<li><a href="../id419939/index.html">Bagaimana saya membuat navigasi di Bereaksi Asli tidak begitu mengerikan</a></li>
<li><a href="../id419941/index.html">Tur Foto Kantor Audiomania: Bagian Satu</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>